version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery

  celery:
    build: ./backend
    command: celery -A dialyproject worker -l info
    volumes:
      - ./backend:/code
    tty: true
    depends_on:
      - redis

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    restart: always

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
