services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    image: eeacms/celery:5.2-1.0
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"  # Redisをブローカーに指定
      CELERY_BACKEND_URL: "db+postgresql://postgres@db/postgres"  # PostgreSQLをバックエンドに指定
      REQUIREMENTS: |
          nltk
          requests
          sqlalchemy
          psycopg2-binary
          redis
      CONSTRAINTS: |
        nltk==3.4
        requests==2.21.0
        sqlalchemy>=1.3.0
        psycopg2-binary>=2.8.0
        redis>=4.0.0
    depends_on:
      - redis
      - db  # 結果バックエンドに依存
    volumes:
      - ./backend:/code

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    restart: always


  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
